using System;
using System.Collections.Generic;
using System.Text;
using Top.Api;
using Top.Api.Request;
using Top.Api.Response;

namespace YapartMarket.BL.Implementation
{
    public class AliExpressCreateLogisticWarehouseOrderService
    {
        //public void a()
        //{
        //    ITopClient client = new DefaultTopClient(url, appkey, secret);
        //    AliexpressLogisticsCreatewarehouseorderRequest req = new AliexpressLogisticsCreatewarehouseorderRequest();
        //    AliexpressLogisticsCreatewarehouseorderRequest.AddressdtosDomain obj1 = new AliexpressLogisticsCreatewarehouseorderRequest.AddressdtosDomain();
        //    AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareAddressDtoDomain obj2 = new AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareAddressDtoDomain();
        //    obj2.Phone = "098-234234";
        //    obj2.Fax = "234234234";
        //    obj2.MemberType = "类型";
        //    obj2.TrademanageId = "cn234234234";
        //    obj2.Street = "street";
        //    obj2.Country = "RU";
        //    obj2.City = "Moscow";
        //    obj2.County = "county";
        //    obj2.Email = "alibaba@alibaba.com";
        //    obj2.AddressId = 1000L;
        //    obj2.Name = "Linda";
        //    obj2.Province = "Moscow";
        //    obj2.StreetAddress = "street address";
        //    obj2.Mobile = "18766234324";
        //    obj2.PostCode = "056202";
        //    obj1.Sender = obj2;
        //    AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareAddressDtoDomain obj3 = new AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareAddressDtoDomain();
        //    obj3.Phone = "098-234234";
        //    obj3.Fax = "234234234";
        //    obj3.MemberType = "类型";
        //    obj3.TrademanageId = "cn234234234";
        //    obj3.Street = "street";
        //    obj3.Country = "RU";
        //    obj3.City = "Moscow";
        //    obj3.County = "county";
        //    obj3.Email = "alibaba@alibaba.com";
        //    obj3.AddressId = 1000L;
        //    obj3.Name = "Linda";
        //    obj3.Province = "Moscow";
        //    obj3.StreetAddress = "street address";
        //    obj3.Mobile = "18766234324";
        //    obj3.PostCode = "056202";
        //    obj1.Pickup = obj3;
        //    AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareAddressDtoDomain obj4 = new AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareAddressDtoDomain();
        //    obj4.Phone = "098-234234";
        //    obj4.Fax = "234234234";
        //    obj4.MemberType = "类型";
        //    obj4.TrademanageId = "cn234234234";
        //    obj4.Street = "street";
        //    obj4.PostCode = "056202";
        //    obj4.Country = "RU";
        //    obj4.City = "Moscow";
        //    obj4.County = "county";
        //    obj4.Email = "alibaba@alibaba.com";
        //    obj4.AddressId = 1000L;
        //    obj4.Name = "Linda";
        //    obj4.Province = "Moscow";
        //    obj4.StreetAddress = "street address";
        //    obj4.Mobile = "18766234324";
        //    obj1.Receiver = obj4;
        //    AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareAddressDtoDomain obj5 = new AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareAddressDtoDomain();
        //    obj5.Phone = "098-234234";
        //    obj5.Fax = "234234234";
        //    obj5.MemberType = "类型";
        //    obj5.TrademanageId = "cn234234234";
        //    obj5.Street = "street";
        //    obj5.Country = "RU";
        //    obj5.City = "Moscow";
        //    obj5.County = "county";
        //    obj5.Email = "alibaba@alibaba.com";
        //    obj5.AddressId = 1000L;
        //    obj5.Name = "Linda";
        //    obj5.Province = "Moscow";
        //    obj5.StreetAddress = "street address";
        //    obj5.Mobile = "18766234324";
        //    obj5.PostCode = "056202";
        //    obj1.Refund = obj5;
        //    req.AddressDTOs_ = obj1;
        //    List<AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareProductForTopDtoDomain> list7 = new List<AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareProductForTopDtoDomain>();
        //    AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareProductForTopDtoDomain obj8 = new AliexpressLogisticsCreatewarehouseorderRequest.AeopWlDeclareProductForTopDtoDomain();
        //    list7.Add(obj8);
        //    obj8.AneroidMarkup = false;
        //    obj8.Breakable = false;
        //    obj8.CategoryCnDesc = "连衣裙";
        //    obj8.CategoryEnDesc = "dress";
        //    obj8.ContainsBattery = false;
        //    obj8.HsCode = "77234";
        //    obj8.OnlyBattery = false;
        //    obj8.ProductDeclareAmount = "1.3";
        //    obj8.ProductId = 1000L;
        //    obj8.ProductNum = 2L;
        //    obj8.ProductWeight = "1.5";
        //    obj8.ScItemCode = "scItem code";
        //    obj8.ScItemId = 1000L;
        //    obj8.ScItemName = "scItem name";
        //    obj8.SkuCode = "sku code";
        //    obj8.SkuValue = "sku value";
        //    obj8.ContainsSpecialGoods = false;
        //    obj8.ChildOrderId = 1000172130022100L;
        //    req.DeclareProductDTOs_ = list7;
        //    req.DomesticLogisticsCompany = "tiantiankuaidi";
        //    req.DomesticLogisticsCompanyId = 505L;
        //    req.DomesticTrackingNo = "L12345899";
        //    req.PackageNum = 1L;
        //    req.TradeOrderFrom = "ESCROW";
        //    req.TradeOrderId = 66715700375804L;
        //    req.UndeliverableDecision = 0L;
        //    req.WarehouseCarrierService = "CPAM_WLB_FPXSZ;CPAM_WLB_CPHSH;CPAM_WLB_ZTOBJ;HRB_WLB_ZTOGZ;HRB_WLB_ZTOSH";
        //    req.InvoiceNumber = "38577123";
        //    req.TopUserKey = "xxxxxxx";
        //    AliexpressLogisticsCreatewarehouseorderRequest.MoneyDomain obj9 = new AliexpressLogisticsCreatewarehouseorderRequest.MoneyDomain();
        //    obj9.Cent = 99L;
        //    obj9.CurrencyCode = "USD";
        //    req.InsuranceCoverage_ = obj9;
        //    AliexpressLogisticsCreatewarehouseorderResponse rsp = client.Execute(req, sessionKey);
        //    Console.WriteLine(rsp.Body);
        //}
    }
}
